# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'busted.ui'
#
# Created: Sat Feb 10 13:09:15 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StudentEdit(object):
    def setupUi(self, StudentEdit):
        StudentEdit.setObjectName(_fromUtf8("StudentEdit"))
        StudentEdit.resize(1200, 900)
        StudentEdit.setMaximumSize(QtCore.QSize(1200, 900))
        self.StudentLabel_Grade = QtGui.QLabel(StudentEdit)
        self.StudentLabel_Grade.setGeometry(QtCore.QRect(530, 200, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentLabel_Grade.setFont(font)
        self.StudentLabel_Grade.setObjectName(_fromUtf8("StudentLabel_Grade"))
        self.StudentText_Grade = QtGui.QLineEdit(StudentEdit)
        self.StudentText_Grade.setGeometry(QtCore.QRect(650, 200, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentText_Grade.setFont(font)
        self.StudentText_Grade.setObjectName(_fromUtf8("StudentText_Grade"))
        self.StudentText_Name = QtGui.QLineEdit(StudentEdit)
        self.StudentText_Name.setGeometry(QtCore.QRect(650, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentText_Name.setFont(font)
        self.StudentText_Name.setObjectName(_fromUtf8("StudentText_Name"))
        self.StudentLabel_ID = QtGui.QLabel(StudentEdit)
        self.StudentLabel_ID.setGeometry(QtCore.QRect(530, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentLabel_ID.setFont(font)
        self.StudentLabel_ID.setObjectName(_fromUtf8("StudentLabel_ID"))
        self.StudentLabel_Picture_2 = QtGui.QLabel(StudentEdit)
        self.StudentLabel_Picture_2.setGeometry(QtCore.QRect(530, 460, 361, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentLabel_Picture_2.setFont(font)
        self.StudentLabel_Picture_2.setObjectName(_fromUtf8("StudentLabel_Picture_2"))
        self.StudentLabel_SearchID = QtGui.QLabel(StudentEdit)
        self.StudentLabel_SearchID.setGeometry(QtCore.QRect(300, 630, 91, 16))
        self.StudentLabel_SearchID.setObjectName(_fromUtf8("StudentLabel_SearchID"))
        self.StudentText_ID = QtGui.QLineEdit(StudentEdit)
        self.StudentText_ID.setGeometry(QtCore.QRect(650, 130, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentText_ID.setFont(font)
        self.StudentText_ID.setObjectName(_fromUtf8("StudentText_ID"))
        self.StudentButton_Remove = QtGui.QPushButton(StudentEdit)
        self.StudentButton_Remove.setGeometry(QtCore.QRect(380, 780, 101, 23))
        self.StudentButton_Remove.setObjectName(_fromUtf8("StudentButton_Remove"))
        self.StudentButton_Exit = QtGui.QPushButton(StudentEdit)
        self.StudentButton_Exit.setGeometry(QtCore.QRect(790, 780, 75, 23))
        self.StudentButton_Exit.setObjectName(_fromUtf8("StudentButton_Exit"))
        self.StudentSearch_ID = QtGui.QLineEdit(StudentEdit)
        self.StudentSearch_ID.setGeometry(QtCore.QRect(300, 660, 161, 31))
        self.StudentSearch_ID.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.StudentSearch_ID.setObjectName(_fromUtf8("StudentSearch_ID"))
        self.StudentButton_Edit = QtGui.QPushButton(StudentEdit)
        self.StudentButton_Edit.setGeometry(QtCore.QRect(250, 780, 91, 23))
        self.StudentButton_Edit.setObjectName(_fromUtf8("StudentButton_Edit"))
        self.LogOffAdmin = QtGui.QCommandLinkButton(StudentEdit)
        self.LogOffAdmin.setGeometry(QtCore.QRect(1100, 10, 187, 41))
        self.LogOffAdmin.setObjectName(_fromUtf8("LogOffAdmin"))
        self.StudentText_RFID = QtGui.QLineEdit(StudentEdit)
        self.StudentText_RFID.setGeometry(QtCore.QRect(650, 340, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentText_RFID.setFont(font)
        self.StudentText_RFID.setObjectName(_fromUtf8("StudentText_RFID"))
        self.StudentText_GName = QtGui.QLineEdit(StudentEdit)
        self.StudentText_GName.setGeometry(QtCore.QRect(650, 270, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentText_GName.setFont(font)
        self.StudentText_GName.setObjectName(_fromUtf8("StudentText_GName"))
        self.StudentLabel_Name = QtGui.QLabel(StudentEdit)
        self.StudentLabel_Name.setGeometry(QtCore.QRect(530, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentLabel_Name.setFont(font)
        self.StudentLabel_Name.setObjectName(_fromUtf8("StudentLabel_Name"))
        self.StudentLabel_Picture = QtGui.QLabel(StudentEdit)
        self.StudentLabel_Picture.setGeometry(QtCore.QRect(530, 410, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentLabel_Picture.setFont(font)
        self.StudentLabel_Picture.setObjectName(_fromUtf8("StudentLabel_Picture"))
        self.StudentLabel_SearchName = QtGui.QLabel(StudentEdit)
        self.StudentLabel_SearchName.setGeometry(QtCore.QRect(10, 630, 91, 16))
        self.StudentLabel_SearchName.setObjectName(_fromUtf8("StudentLabel_SearchName"))
        self.StudentText_Picture = QtGui.QLineEdit(StudentEdit)
        self.StudentText_Picture.setGeometry(QtCore.QRect(650, 410, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentText_Picture.setFont(font)
        self.StudentText_Picture.setObjectName(_fromUtf8("StudentText_Picture"))
        self.StudentSearch_Name = QtGui.QLineEdit(StudentEdit)
        self.StudentSearch_Name.setGeometry(QtCore.QRect(10, 660, 281, 31))
        self.StudentSearch_Name.setObjectName(_fromUtf8("StudentSearch_Name"))
        self.StudentLabel_RFID = QtGui.QLabel(StudentEdit)
        self.StudentLabel_RFID.setGeometry(QtCore.QRect(530, 340, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentLabel_RFID.setFont(font)
        self.StudentLabel_RFID.setObjectName(_fromUtf8("StudentLabel_RFID"))
        self.StudentButton_Add = QtGui.QPushButton(StudentEdit)
        self.StudentButton_Add.setGeometry(QtCore.QRect(120, 780, 91, 23))
        self.StudentButton_Add.setObjectName(_fromUtf8("StudentButton_Add"))
        self.StudentLabel_GName = QtGui.QLabel(StudentEdit)
        self.StudentLabel_GName.setGeometry(QtCore.QRect(530, 270, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentLabel_GName.setFont(font)
        self.StudentLabel_GName.setObjectName(_fromUtf8("StudentLabel_GName"))
        self.StudentView = QtGui.QListView(StudentEdit)
        self.StudentView.setGeometry(QtCore.QRect(10, 60, 450, 550))
        self.StudentView.setObjectName(_fromUtf8("StudentView"))

        self.retranslateUi(StudentEdit)
        QtCore.QMetaObject.connectSlotsByName(StudentEdit)

    def retranslateUi(self, StudentEdit):
        StudentEdit.setWindowTitle(_translate("StudentEdit", "Student Edit", None))
        self.StudentLabel_Grade.setText(_translate("StudentEdit", "Grade Number:", None))
        self.StudentLabel_ID.setText(_translate("StudentEdit", "Student ID:", None))
        self.StudentLabel_Picture_2.setText(_translate("StudentEdit", "Picture", None))
        self.StudentLabel_SearchID.setText(_translate("StudentEdit", "Search ID:", None))
        self.StudentButton_Remove.setText(_translate("StudentEdit", "Remove Student", None))
        self.StudentButton_Exit.setText(_translate("StudentEdit", "Exit", None))
        self.StudentButton_Edit.setText(_translate("StudentEdit", "Edit Student", None))
        self.LogOffAdmin.setText(_translate("StudentEdit", "Log Off", None))
        self.StudentLabel_Name.setText(_translate("StudentEdit", "Full Name:", None))
        self.StudentLabel_Picture.setText(_translate("StudentEdit", "Picture:", None))
        self.StudentLabel_SearchName.setText(_translate("StudentEdit", "Search Name:", None))
        self.StudentLabel_RFID.setText(_translate("StudentEdit", "Tag ID:", None))
        self.StudentButton_Add.setText(_translate("StudentEdit", "Add Student", None))
        self.StudentLabel_GName.setText(_translate("StudentEdit", "Guardian:", None))

